apiVersion: v1
kind: Service
metadata:
  name: auth-blue
  namespace: utopia
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: auth
    version: ${VERSION}
  type: LoadBalancer
