apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flight
  name: flight-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: flight # minikube load image <image-name>
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: UTOPIA_DB_HOST
              value: $(UTOPIA_DB_HOST)
            - name: UTOPIA_DB_NAME
              value: $(UTOPIA_DB_NAME)
            - name: UTOPIA_DB_PASSWORD
              value: $(UTOPIA_DB_PASSWORD)
            - name: UTOPIA_DB_PORT
              value: $(UTOPIA_DB_PORT)
            - name: UTOPIA_DB_USER
              value: $(UTOPIA_DB_USER)
            - name: UTOPIA_JWT_SECRET
              value: $(UTOPIA_JWT_SECRET)
            - name: UTOPIA_MICROSERVICE_FLIGHTS_PORT
              value: $(UTOPIA_MICROSERVICE_FLIGHTS_PORT)
---
apiVersion: v1
kind: Service
metadata:
  name: flight-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: flight
