apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user # minikube load image <image-name>
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: UTOPIA_DB_HOST
              value: $(UTOPIA_DB_HOST)
            - name: UTOPIA_DB_NAME
              value: $(UTOPIA_DB_NAME)
            - name: UTOPIA_DB_PASSWORD
              value: $(UTOPIA_DB_PASSWORD)
            - name: UTOPIA_DB_PORT
              value: $(UTOPIA_DB_PORT)
            - name: UTOPIA_DB_USER
              value: $(UTOPIA_DB_USER)
            - name: UTOPIA_JWT_SECRET
              value: $(UTOPIA_JWT_SECRET)
            - name: UTOPIA_MICROSERVICE_USERS_PORT
              value: $(UTOPIA_MICROSERVICE_USERS_PORT)
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  selector:
    app: user
