apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utopia
  labels:
    app: auth
    app.kubernetes.io/name: utopia-auth
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: utopia-auth
      app: auth
  template:
    metadata:
      labels:
        app: auth
        app.kubernetes.io/name: utopia-auth
    spec:
      containers:
        - name: auth
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nr-utopia-auth
          ports:
            - containerPort: 8084
          env:
            - name: UTOPIA_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db_host
                  name: utopia-secret
            - name: UTOPIA_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: utopia-secret
            - name: UTOPIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: utopia-secret
            - name: UTOPIA_DB_PORT
              valueFrom:
                secretKeyRef:
                  key: db_port
                  name: utopia-secret
            - name: UTOPIA_DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: utopia-secret
            - name: UTOPIA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: utopia-secret
            - name: UTOPIA_MICROSERVICE_AUTH_PORT
              valueFrom:
                secretKeyRef:
                  key: auth_port
                  name: utopia-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: utopia
  name: auth-service
  labels:
    app: auth
    app.kubernetes.io/name: utopia-auth
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  selector:
    app.kubernetes.io/name: utopia-auth
