apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: utopia-cluster
  region: us-west-2

vpc:
  id: ${VPC_ID}

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: fp-utopia
    selectors:
      - namespace: utopia

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
