apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utopia
  labels:
    app: flight
    app.kubernetes.io/name: utopia-flight
  name: flight-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
      app.kubernetes.io/name: utopia-flight
  template:
    metadata:
      labels:
        app: flight
        app.kubernetes.io/name: utopia-flight
    spec:
      containers:
        - name: flight
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nr-utopia-flight
          ports:
            - containerPort: 8081
          env:
            - name: UTOPIA_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db_host
                  name: utopia-secret
            - name: UTOPIA_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: utopia-secret
            - name: UTOPIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: utopia-secret
            - name: UTOPIA_DB_PORT
              valueFrom:
                secretKeyRef:
                  key: db_port
                  name: utopia-secret
            - name: UTOPIA_DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: utopia-secret
            - name: UTOPIA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: utopia-secret
            - name: UTOPIA_MICROSERVICE_FLIGHTS_PORT
              valueFrom:
                secretKeyRef:
                  key: flight_port
                  name: utopia-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: utopia
  name: flight-service
  labels:
    app: flight
    app.kubernetes.io/name: utopia-flight
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app.kubernetes.io/name: utopia-flight
