node('agent1') {
    stage('Preparation') {
        git 'https://github.com/Heads-in-the-Cloud/devops-NR.git'
    }
    stage('Create cluster') {
        sh 'eksctl create cluster eks/eks-config.yml'
    }
    stage('Add lb charts') {
        sh 'kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"'
        sh 'helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=utopia-cluster --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=us-west-2 --set vpcId=${VPC_ID}'
    }
    stage('Deploy') {
        sh 'kubectl apply -f eks/'
    }
}
