pipeline {
    agent any

    environment {
        VPC_ID = credentials('vpc_id')
        AWS_REGION = credentials('aws_region')
        utopia_secret = credentials('utopia_secret')
    }

    stages {
        stage('Create cluster') {
            sh 'eksctl create cluster -f eks/eks-config.yml'
        }
        stage('Add lb charts') {
            sh 'kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"'
            sh 'helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=utopia-cluster --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=${AWS_REGION} --set vpcId=${VPC_ID}'
        }
        stage('Deploy') {
            sh 'cp $utopia_secret eks/'
            sh 'kubectl apply -f eks/namespace.yml'
            sh 'kubectl apply -f eks/'
        }
    }
}