apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "utopia-microservices.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "utopia-microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "utopia-microservices.labels" . | nindent 8 }}
      annotations:
        fluentbit.io/parser: cri
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.aws.id }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/nr-utopia-{{ .Release.Name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: UTOPIA_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db_host
                  name: utopia-secret
            - name: UTOPIA_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: utopia-secret
            - name: UTOPIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: utopia-secret
            - name: UTOPIA_DB_PORT
              valueFrom:
                secretKeyRef:
                  key: db_port
                  name: utopia-secret
            - name: UTOPIA_DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: utopia-secret
            - name: UTOPIA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: utopia-secret
            - name: UTOPIA_MICROSERVICE_PORT
              valueFrom:
                secretKeyRef:
                  key: microservice_port
                  name: utopia-secret
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}

