version: "3"
services:
  auth-microservice:
    image: auth
    container_name: auth
    ports:
      - "${UTOPIA_MICROSERVICE_AUTH_PORT}:${UTOPIA_MICROSERVICE_AUTH_PORT}"
  user-microservice:
    image: user
    container_name: user
    ports:
      - "${UTOPIA_MICROSERVICE_USERS_PORT}:${UTOPIA_MICROSERVICE_USERS_PORT}"
  flight-microservice:
    image: flight
    container_name: flight
    ports:
      - "${UTOPIA_MICROSERVICE_FLIGHTS_PORT}:${UTOPIA_MICROSERVICE_FLIGHTS_PORT}"
  booking-microservice:
    image: booking
    container_name: booking
    ports:
      - "${UTOPIA_MICROSERVICE_BOOKINGS_PORT}:${UTOPIA_MICROSERVICE_BOOKINGS_PO\
        RT}"
  orchestrator:
    image: orchestrator
    container_name: orchestrator
    ports:
      - "${UTOPIA_MICROSERVICE_ORCHESTRATOR_PORT}:${UTOPIA_MICROSERVICE_ORCHEST\
        RATOR_PORT}"
