pipeline {
    agent { label 'aws-ready' }

    stages {
        stage('Run TFlint') {
            steps {
                dir("terratest/terraform/") {
                    sh 'tflint --init'
                    sh 'tflint'
                }
            }
            post {
                success {
                    echo 'tflint passed'
                }
            }
        }
        stage('Run Terratest') {
            steps {
                dir("terratest/test/") {
                    sh 'rm go.mod && rm go.sum'
                    sh 'go mod init network'
                    sh 'go mod tidy'
                    sh 'go test network_test.go -v -timeout 30m'
                }
            }
            post{
                failure {
                    sh 'echo test failed'
                }
            }
        }
        stage('Terraform init') {
            steps {
                dir("terratest/terraform/") {
                    script {
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Terraform plan') {
            steps {
                dir("terratest/terraform/") {
                    script {
                        sh 'terraform plan'
                    }
                }
            }
        }
    }
}